# Generated by Django 4.0.2 on 2023-10-10 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=100)),
                ('client_name', models.CharField(max_length=100)),
                ('client_phone', models.CharField(max_length=15)),
            ],
        ),
    ]
