# Generated by Django 4.0.2 on 2023-10-11 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryroute',
            name='pedido',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='deliveryroute',
            name='qtd',
            field=models.IntegerField(default=1),
        ),
    ]
