# Generated by Django 4.0.2 on 2023-10-12 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_deliveryroute_pedido_deliveryroute_qtd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryroute',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
