# Generated by Django 4.2.6 on 2023-10-12 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_alter_deliverystatus_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverystatus',
            name='status',
            field=models.CharField(choices=[('Pedente', 'Pedente'), ('Entregue', 'Entregue')], default='Pedente', max_length=10),
        ),
    ]
