# Generated by Django 4.2.6 on 2023-10-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0008_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='foto',
            field=models.ImageField(default='default.jpg', upload_to='imagenes/'),
        ),
    ]
